In [1]:
import pandapower.networks as pn

In [1]:
net = pn.create_cigre_network_mv(with_der="all")

In [2]:
net

This pandapower network includes the following parameter tables:
   - bus (15 elements)
   - load (18 elements)
   - sgen (13 elements)
   - storage (2 elements)
   - switch (8 elements)
   - ext_grid (1 element)
   - line (15 elements)
   - trafo (2 elements)
   - bus_geodata (15 elements)

In [3]:
net.sgen

,name,bus,p_mw,q_mvar,sn_mva,scaling,in_service,type,current_source
0,PV 3,3,0.020,0.0,0.020,1.0,True,PV,True
1,PV 4,4,0.020,0.0,0.020,1.0,True,PV,True
2,PV 5,5,0.030,0.0,0.030,1.0,True,PV,True
3,PV 6,6,0.030,0.0,0.030,1.0,True,PV,True
4,PV 8,8,0.030,0.0,0.030,1.0,True,PV,True
5,PV 9,9,0.030,0.0,0.030,1.0,True,PV,True
6,PV 10,10,0.040,0.0,0.040,1.0,True,PV,True
7,PV 11,11,0.010,0.0,0.010,1.0,True,PV,True
8,WKA 7,7,1.500,0.0,1.500,1.0,True,WP,True
9,Residential fuel cell 1,5,0.033,0.0,0.033,1.0,True,Residential fuel cell,True
10,CHP diesel 1,9,0.310,0.0,0.310,1.0,True,CHP diesel,True
11,Fuel cell 1,9,0.212,0.0,0.212,1.0,True,Fuel cell,True
12,Residential fuel cell 2,10,0.014,0.0,0.014,1.0,True,Residential fuel cell,True

In [4]:
net.sgen['p_mw'][4] = 5

In [5]:
net.sgen

,name,bus,p_mw,q_mvar,sn_mva,scaling,in_service,type,current_source
0,PV 3,3,0.020,0.0,0.020,1.0,True,PV,True
1,PV 4,4,0.020,0.0,0.020,1.0,True,PV,True
2,PV 5,5,0.030,0.0,0.030,1.0,True,PV,True
3,PV 6,6,0.030,0.0,0.030,1.0,True,PV,True
4,PV 8,8,5.000,0.0,0.030,1.0,True,PV,True
5,PV 9,9,0.030,0.0,0.030,1.0,True,PV,True
6,PV 10,10,0.040,0.0,0.040,1.0,True,PV,True
7,PV 11,11,0.010,0.0,0.010,1.0,True,PV,True
8,WKA 7,7,1.500,0.0,1.500,1.0,True,WP,True
9,Residential fuel cell 1,5,0.033,0.0,0.033,1.0,True,Residential fuel cell,True
10,CHP diesel 1,9,0.310,0.0,0.310,1.0,True,CHP diesel,True
11,Fuel cell 1,9,0.212,0.0,0.212,1.0,True,Fuel cell,True
12,Residential fuel cell 2,10,0.014,0.0,0.014,1.0,True,Residential fuel cell,True

In [ ]:
solarRatings = []